# Generated by Django 4.0.4 on 2022-11-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainer', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('OFFENSIVE', 'OFFENSIVE'), ('NOFFENSIVE', 'NOFFENSIVE')], max_length=10, null=True)),
                ('social_media', models.CharField(choices=[('OFFENSIVE', 'OFFENSIVE'), ('NOFFENSIVE', 'NOFFENSIVE')], max_length=10, null=True)),
                ('messager_id', models.CharField(max_length=255)),
                ('message', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='pix')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(editable=False, max_length=255)),
                ('rpwd', models.CharField(editable=False, max_length=255)),
            ],
        ),
    ]
