# Generated by Django 4.0.4 on 2022-11-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bully', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='social_media',
            field=models.CharField(choices=[('FACEBOOK', 'FACEBOOK'), ('INSTAGRAM', 'INSTAGRAM'), ('TWITTER', 'TWITTER')], max_length=10, null=True),
        ),
    ]
